name: Auto review assign

on: push

jobs:
  reviews-assign:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: medric/auto-review-assign-action
      - name: Hello world action step
        uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
