name: Auto review assign

on: [pull_request]

jobs:
  assigns-if-fail:
    runs-on: ubuntu-latest
    name: Assigns if fail
    steps:
      - name: Do something with a failing build
        uses: medric/auto-review-assign-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: medric
