name: Auto review assign

on: [pull_request]

jobs:
  reviews-assign:
    runs-on: ubuntu-latest
    name: Assign if fail
    steps:
      - name: Do something with a failing build
        uses: medric/auto-review-assign-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: webschool
