name: Auto approve

on: pull_request

jobs:
  reviews-assign:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: medric/actions
      - name: Hello world action step
        uses: ./review-assign
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
