name: Auto request review
on: pull_request

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout GitHub Label Dependabot PR
      #   uses: actions/checkout@v2
      #   # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      #   with:
      #     repository: airtasker/label-dependabot-pr-action
      #     ref: master
      #     token: ${{ secrets.REPO_TOKEN }} # stored in GitHub secrets
      #     path: .github/actions/label-dependabot-pr
      - name: Checkout GitHub Request Review
        uses: actions/checkout@v2
        # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          repository: airtasker/auto-request-review-action
          ref: 6668b1075323af199d7d5e1013740aedbd4c6b3c
          token: ${{ secrets.REPO_TOKEN }} # stored in GitHub secrets
          path: .github/actions/auto-request-review-action
      # - name: Run label-dependabot-pr
      #   id: label
      #   uses: ./.github/actions/label-dependabot-pr
      #   # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      #   with:
      #     github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Run auto request review
        uses: ./.github/actions/auto-request-review-action
        # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.REPO_TOKEN }}'
          reviewers: web school # or a comma-separated list of Github usernames
          forceRequestReview: ${{ steps.label.outputs.releaseLabel == 'major' }}
