name: Auto review assign

on: [push,pull_request]

jobs:
  reviews-assign:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: github.event.pull_request.head.sha || github.sha

      - name: Do something with a passing build
        run: |
          echo "All checks have passed"
        if: steps.wait-for-build.outputs.conclusion == 'success'

      - name: Do something with a failing build
        uses: medric/auto-review-assign-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: webschool
        if: steps.wait-for-build.outputs.conclusion == 'failure'
